apiVersion: apps/v1
kind: Deployment
metadata:
  name: mexp-deploy
  labels:
    app: express
spec:
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: mongo
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mdb-secrets
                  key: username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mdb-secrets
                  key: password
            - name: ME_CONFIG_MONGODB_SERVER
              value: mdb-svc
          